mkrepo: add zstd deb package as dependency
tarantool/rws pull request #68
Opened 2022-07-21 15:55 UTC by ylobankov

This patch adds the `zstd` deb package as a dependency that is needed
for the `mkrepo` library. The dependency is stored in the special file
`apt-packages` that can be read by Dokku service and installed while
RWS deployment.

2022-07-21 15:59 UTC, artembo approved these changes

2022-07-21 19:55 UTC, LeonidVas requested changes
Hi! Thank you for the patch.
Generally I'm OK, but I have several comments/questions:
- add a comment to the `apt-packages` file that `zstd is needed for `mkrepo`
- maybe [`Aptfile`](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt) would be a better choice, as I [understood from google](https://stackoverflow.com/a/60471998) it should support both `heroku` and `dokku`?

2022-07-22 09:16 UTC, ylobankov commented
> * add a comment to the `apt-packages` file that `zstd is needed for `mkrepo`

Done.


> * maybe [`Aptfile`](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt) would be a better choice, as I [understood from google](https://stackoverflow.com/a/60471998) it should support both `heroku` and `dokku`?

Unfortunately, it doesn't work.


> * fill the `CHANGELOG.md` (like [here](https://github.com/tarantool/cartridge-cli/blob/master/CHANGELOG.md?rgh-link-date=2022-07-21T19%3A55%3A21Z#unreleased))

Done.

2022-07-22 10:04 UTC, LeonidVas approved these changes
LGTM

2022-07-22 10:04 UTC, merged